### ISSUE TITLE
bump up max upload for metalnx to 100 GB

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#143]
upgrade max upload size

**Comment by mtridici** [comment]
I'm sorry, but I'm still experiencing this kind of problem.
I followed docker-compose installation: all services are up & running, but if I try to download a 5GB sized file, I notice that the browser download window shows a 1,4GB size.

I'm using docker-compose in order to reduce the errors I could do. the docker host is a CentOS 7.8 virtual machine. Is there some suggestion about OS to be used for the docker host or some specific dependencies to be satisfied?

I Installed also DFC-Cloud Browser and I'm facing the same problem.

Thanks, Mauro
