### ISSUE TITLE
configuration in metalnx.properties

### ISSUE THREAD

**Issue by yr-wang-hit** [irods-contrib/metalnx-web#273]
Dear Metalnx Team

we have test metalnx2.4.0 with irods4.2.8. Everything goes well But unfortunately the metadata search service is unavailable.

The error log tells that the user id invalid.But it is hard to understand because we indeed login successfully. 

I checked the irods user with icommand "iadmin lu" and find that when I create a user through metalnx without password(the password field can be set empty), the user is successfully created but it can never login.

I find that the metalnx.properties configuration has some hard-to-understand fields called [job.user]  ｜ [job.password] ｜ [jwt.*], What are they used for? and I feel confused to tell the difference between the fields and [irods.admin], [irods.password]. How to configure them to make the search service run?

I wonder if different clients share the same search service by configuring it on the server side. The design, together with separate metalnx db architecture feels really strange and I need your help badly to make it more clear.

Thanks

**Comment by trel** [comment]
Hi,

I agree the metalnx.properties file needs some work - we'll be cleaning it out a bit soon as Metalnx loses its admin capabilities (see [roadmap.md](https://github.com/irods-contrib/metalnx-web/blob/master/roadmap.md)).

That said, yes, the `jobs.irods.usernam` and `jobs.irods.password` need to represent a rodsadmin account (can be the same as defined in `irods.admin.user` and `irods.admin.password`) so that Metalnx can populate and cache its own information from the iRODS catalog in the Metalnx local database.  I'm not sure the original reason for not re-using `jobs.irods.username` and `jobs.irods.password` for that work.

The built-in search (AVU Search) should be working today, if the `jobs.*` properties are correct and can do the AVU caching correctly.

The `jwt.*` properties are used to communicate with the pluggablesearch system, which is turned off by default.  It is being made to work in concert with the [iRODS indexing plugin](https://github.com/irods/irods_capability_indexing/) at the moment and should be more documented in the next release.

Creating and managing users via Metalnx does have some holes/bugs (like you said, with an empty password), but we do not intend to debug/fix those, rather we'll be removing the admin capabilities completely in deference to the new [ZMT](https://github.com/irods/irods_client_zone_management_tool).

Thanks.

**Comment by yr-wang-hit** [comment]
Thanks for your reply, terrell.
