### ISSUE TITLE
Permission error in collections - oci sql error in irods

### ISSUE THREAD

**Issue by revna** [irods-contrib/metalnx-web#5]
with irods 4.1.10 (icat oracle database)
and metalnx (postgres)

we have an permission error (for all collections) in metalnx from sql error in irods server log

```
ERROR: bindVar[1]=:/:
ERROR: bindVar[2]=:rods:
ERROR: cllExecSqlWithResult OCIStmtExecute error: -1, sql:SELECT R_USER_MAIN.user_name, R_USER_MAIN.user_id, R_OBJT_ACCESS.access_type_id, R_USER_MAIN.user_type_name, R_USER_MAIN.zone_name, R_COLL_MAIN.coll_name, USER_GROUP_MAIN.user_name, R_COLL_MAIN.coll_name FROM R_USER_MAIN AS USER_GROUP_MAIN JOIN R_USER_GROUP JOIN R_USER_MAIN ON R_USER_GROUP.user_id = R_USER_MAIN.user_id ON USER_GROUP_MAIN.user_id = R_USER_GROUP.group_user_id JOIN R_OBJT_ACCESS ON R_USER_GROUP.group_user_id = R_OBJT_ACCESS.user_id JOIN R_COLL_MAIN ON R_OBJT_ACCESS.object_id = R_COLL_MAIN.coll_id WHERE R_COLL_MAIN.coll_name = :1 AND R_USER_MAIN.user_name = :2 ORDER BY R_COLL_MAIN.coll_name, R_USER_MAIN.user_name, R_OBJT_ACCESS.access_type_id DESC
ERROR: OCI_Error: ORA-00933: SQL-Befehl wurde nicht korrekt beendet
NOTICE: chlSpecificQuery cmlGetFirstRowFromSql failure -806000
NOTICE: _rsSpecificQuery: specificQuery status = -806000
NOTICE: rsSpecificQuery: rcSpecificQuery failed, status = -806000
```

error in sql statement occurs in "FROM R_USER_MAIN **AS** USER_GROUP_MAIN"
an alias for a table is correct without AS  ???

**Comment by ajguerra** [comment]
Thanks a lot for pointing that out. We are investigating this problem. But before we go any deeper into that, what is the OS you are running both iRODS and Metalnx @revna? 

As soon as we identify the cause of the problem, we will respond you here.

Thank you,

Arthur.

**Comment by revna** [comment]
the error "FROM R_USER_MAIN AS USER_GROUP_MAIN" is an irods error in the table r_specific_query.
after fixing these we have also errors in oracle from metalnx added specific queries .
metalnxListOfDataObjectsThatMatchSearchText:
countDataObjectsThatMatchSearchText (CollectionServiceImpl.java) --> ORA-00972: identifier is too long
and in these query also with "SELECT **DISTINCT ON** (d.data_name)"

metalnxListOfCollectionsThatMatchSearchText
--> there is used  "offset :3 limit :4" not usable in oracle irods db.

**Comment by ngmenyen** [comment]
@revna Am I right to assume that the **cllExecSqlWithResult OCIStmtExecute error** (first post) you got came from Jargon? If it is so, did you download the Jargon code and built it yourself to solve the first problem?

Best regards.

**Comment by revna** [comment]
the reason is the metalnx code. (not jargon or irods)
irods can use mysql, postgres and oracle as database plugin. metalnx creates [specific queries](https://github.com/Metalnx/metalnx-web/search?utf8=%E2%9C%93&q=addSpecificQuery) which are only usable with postgres irods icat database. metalnx uses the jargon [addSpecificQuery ](https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/pub/SpecificQueryAOImpl.java) function only with postgres sql. so irods with oracle db can't process these queries.

examples:
- user specific queries --> searchByMetadata in SpecQueryServiceImpl 
   gb.append(" ) **AS** data_obj_metadata ON (d.data_id = map_object_id) ");

-  in countItemsMatchingFileProperties
   query.append("SELECT COUNT(*) FROM	( " + tableName + " ) **AS** fileProperties  WHERE");

there are many differences for oracle:

- no OFFSET / LIMIT  (rownum)
- ILIKE vs. LIKE
- AS not allowed for table alias
- size not allowed as columname
- identifier max 30 characters

jargon don't transfer these specific direct queries for you. 

btw: 
the standard tomcat upload folder in metalnx is the "tomcat home base" so metalnx create folders in these folder with the logged in username. in normal conditions for usernames "common", "server" or other exiting tomcat folders it is not "very good". please add a simple propertie for tmp upload folder definition

**Comment by ajguerra** [comment]
@revna I think we have a misunderstood @ngmenyen . 

When you opened up this issue you pointed that *error in sql statement occurs in "FROM R_USER_MAIN AS USER_GROUP_MAIN"*. This is a query that is not issued by Metalnx directly. 

Later on, you also said that *"the error "FROM R_USER_MAIN AS USER_GROUP_MAIN" is an irods error in the table r_specific_query" after fixing these we have also errors in oracle from metalnx added specific queries..."*. We were just wondering what fixes you applied to solve this problem, so we could reproduce exactly the same errors as you had and maybe other Oracle users may want to know that too.

But you are right. We do have issues with our SQL queries for Oracle DBs. We already identified most of the problems with them and thanks for point out some others. 

Yes, Jargon does not transfer these specific queries for us because we use SQL statements directly. We did that because at the time Jargon did not offer a very flexible way to paginate DB results as we wanted on the UI. Then, we decided to implement our own pagination mechanism based on direct queries to the iCAT DB (aware that direct SQL queries would not work for all DBs).

I'll file this as a bug since all queries need to be reviewed. We can work on that together (maybe with a contribution? =D).

BTW, we are currently working on some particular issues with the Metalnx upload and microservices. I'll be posting that up very soon, so you can take a look at if you want to.

**Comment by felipegutierrez** [comment]
Hi @ajguerra , I think I have the same problem but in another place of the project. I am wondering how to solve this in a better way.
This [code](https://github.com/Metalnx/metalnx-web/blob/revision1/src/emc-metalnx-services/src/main/java/com/emc/metalnx/services/irods/CollectionServiceImpl.java#L1054) is throwing an error because this [query](https://github.com/Metalnx/metalnx-web/blob/revision1/src/emc-metalnx-services/src/main/java/com/emc/metalnx/services/irods/CollectionServiceImpl.java#L1003) is formed with ILIKE for postgreSQL. I am using MySQL.

I am thinking to create a properties file at the emc-metalnx-services project to identify which database we are using (PostgreSQL, MySQL or Oracle). Load this value at the [ServerUtil.java](https://github.com/Metalnx/metalnx-web/blob/revision1/src/emc-metalnx-services/src/main/java/com/emc/metalnx/services/machine/util/ServerUtil.java) and do the verification before this [code line](https://github.com/Metalnx/metalnx-web/blob/revision1/src/emc-metalnx-services/src/main/java/com/emc/metalnx/services/irods/CollectionServiceImpl.java#L1006).

Or perhaps coping the file `database.properties` through pom.xml to the emc-metalnx-services project. Reading the property `hibernate.dialect=org.hibernate.dialect.MySQL5Dialect` to identify which database we are using. Create a property at [ServerUtil.java](https://github.com/Metalnx/metalnx-web/blob/revision1/src/emc-metalnx-services/src/main/java/com/emc/metalnx/services/machine/util/ServerUtil.java) and do the validation at [CollectionServiceImpl.java](https://github.com/Metalnx/metalnx-web/blob/revision1/src/emc-metalnx-services/src/main/java/com/emc/metalnx/services/irods/CollectionServiceImpl.java#L1006).

What do you think?
I am asking because you may have a better way to solve this since you started the project and I am open to listen.

Best Regards

**Comment by ngmenyen** [comment]
Hi all, 

It is only this SQL statement that is particular to PostgreSQL and does not exist in MySQL. For now, I don't think it is necessary to add a new properties file.

I replaced **ILIKE** by **LIKE** and I also set the compared strings all to uppercase. Right now I'm setting up a new virtual machine with MySQL to test this change.

**Comment by ajguerra** [comment]
yes @felipegutierrez you need to address this issue. The idea of another entry in the `database.properties` file isn't bad at all. But I think we're gonna need a little more than just verify before the code you pointed out. Feel free to post any suggestion or comment here. We're gonna discuss those queries here and see what you're going to do to make this service work great with different DBs. I'll let you know.

Again, thx for your time on this!

**Comment by felipegutierrez** [comment]
Hi @ajguerra. I could do the query to the MySQL database.
I am coping the database.properties from web project to the service project through the main pom.xml. I created a class at the service project to read this file. Afterwards I am using `specificQueryAO.findSpecificQueryByAlias(sqlQueryAlias);` and catching the `DataNotFoundException` to build a new MySQL query. For more details you can check this [link](https://gist.github.com/felipegutierrez/da520c8f22218ee3a7d3d9f009d150ed). 

I think we can figure out a better way with out using catch exception. But since I never worked with Jargon I would like to see if you know elegant approach to do that. I also have another queries to do the same thing. So I preferred to ask before to do the hard work.
What do you think?

**Comment by ajguerra** [comment]
That's great work @felipegutierrez ! Let's work something out together.

So, I was thinking... I'm not sure if we need to copy the `database.properties` into the service project. The service layer is able to read this file since it's in the classpath. Try something like:

```
@Value("${hibernate.dialect}")
private String hibernateDialect;
```

Spring will then fill `hibernateDialect` for you in any service.

I do like the idea of having a `DBPropertiesConfigurer`. It will make other classes that need to know the iCAT DB simpler, easier to read. 

Another thing I had in mind was actually remove some of the reponsabilities this CollectionService has. The method you pointed out is kind of big and this isn't great. What we can do is to make the CollectionService simpler. It doesn't care about the DB. It only cares about the result of the query.

We could maybe create a new service that would resolve the DB (with a little help from `DBPropertiesConfigurer`) and would create the apropriate SQL. That would decouple the CollectionService from the database and let the correct service do the dirty part.

Let me know what you think about that.

**Comment by felipegutierrez** [comment]
Hi @ajguerra .

I modified `DBPropertiesConfigServiceImpl.java` to only get DB configurations and also took out all code from pom.xml and the method that reads `database.properties`.

I created the service `CollectionSqlServiceImpl.java` to return only the string sql from the database we are using.

The method `CollectionServiceImpl.getTotalCollectionsUnderPathThatMatchSearchText()` does not have string queries any more. So, all string queries will be at `CollectionSqlServiceImpl.java`, which extends from the same name with Sql word. What do you think about this pattern? I am asking because we can decide one pattern to apply to all xxxxxSqlServices.

Questions:
1 - The methods at `CollectionSqlServiceImpl.java` should return a `String` or do you prefer to return a `SpecificQueryDefinition`?
2 - I am creating the query alias like this : `sqlQueryAlias += Database.MYSQL.name();`. Is that ok for you? I am asking this because it should be a pattern on the project. So, I understood that jargon has alias only for PostgreSQL. Is that correct?
3 - should I keep the comments `Copyright (c) 2015-2016, EMC Corporation blablabla` on the new classes?

Please, take a look at this link for the [code](https://gist.github.com/felipegutierrez/9fd258e0464ee7dcac3ee9944d74bdbf).

**Comment by felipegutierrez** [comment]
I also fixed the metadata search for MySQL. Now it is supposed to work for PostgreSQL and MySQL.
![screen shot 2017-02-07 at 13 24 31](https://cloud.githubusercontent.com/assets/5030696/22691066/f7aeb3b0-ed38-11e6-8704-37e394ae7f32.png)
@ajguerra please, [check the code](https://github.com/felipegutierrez/metalnx-web/commit/f6623b78603db0e749fc028203e4cd3e55f95446) on my repository to see if I implemented as the design it should be for the future. Any comments are welcome and I can rework on the architecture if you think it is necessary, so we can merge the code.
